CREATE DATABASE IF NOT EXISTS satpolpp_complaint CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE satpolpp_complaint;

CREATE TABLE IF NOT EXISTS training_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text TEXT NOT NULL,
  label VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS complaints (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(100),
  user_phone VARCHAR(30),
  text TEXT NOT NULL,
  predicted_label VARCHAR(100),
  photo_path VARCHAR(255) DEFAULT NULL,
  location VARCHAR(255) DEFAULT NULL,
  latitude DOUBLE DEFAULT NULL,
  longitude DOUBLE DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
