<?php
require __DIR__ . "/../config/database.php";

// $users = [
//     ['Admin Satpol',  'admin@satpolpp.go.id', password_hash('123456', PASSWORD_DEFAULT), 'admin'],
//     ['Petugas Lapangan',  'petugas@satpolpp.go.id', password_hash('123456', PASSWORD_DEFAULT), 'petugas'],
//     ['Warga Contoh',  'user@test.com', password_hash('123456', PASSWORD_DEFAULT), 'masyarakat'],
// ];

// foreach ($users as $u) {
//     $pdo->prepare("INSERT IGNORE INTO users(nama,email,password,role) 
//                    VALUES (?,?,?,?)")
//         ->execute([$u[0], $u[1], password_hash($u[2], PASSWORD_BCRYPT), $u[3]]);
// }

// echo "Default users inserted.\n";

// Dummy training dataset
$data = [
    // --- Klasifikasi: Penertiban Pasar ---
    ['Pedagang kaki lima berjualan di bahu jalan', 'Penertiban Pasar'],
    ['Lapak berdiri di atas saluran air', 'Penertiban Pasar'],
    ['Dagangan menutup trotoar umum', 'Penertiban Pasar'],
    ['Lapak menghalangi pintu ruko', 'Penertiban Pasar'],
    ['Jual beli terjadi di luar zona pasar', 'Penertiban Pasar'],
    ['Gerobak dagang menyebabkan kemacetan', 'Penertiban Pasar'],
    ['Pedagang memakai gang pasar untuk berjualan', 'Penertiban Pasar'],
    ['Bangunan liar digunakan sebagai kios', 'Penertiban Pasar'],
    ['Spanduk dagangan dipasang di tiang listrik', 'Penertiban Pasar'],
    ['Limbah dagang dibuang ke selokan', 'Penertiban Pasar'],
    ['Kios dibangun melebihi batas pasar', 'Penertiban Pasar'],
    ['Barang dagangan memenuhi lorong pasar', 'Penertiban Pasar'],
    ['Area parkir dipakai untuk berjualan', 'Penertiban Pasar'],
    ['Tenda dagang berdiri tanpa izin', 'Penertiban Pasar'],
    ['Lapak ilegal disewakan ke pedagang lain', 'Penertiban Pasar'],
    ['Etalase menutup jalur pejalan kaki', 'Penertiban Pasar'],
    ['Lapak berdiri di zebra cross', 'Penertiban Pasar'],
    ['Meja dagang menghalangi akses pasar', 'Penertiban Pasar'],
    ['Pedagang berjualan di depan sekolah', 'Penertiban Pasar'],
    ['Lapak berdiri di atas drainase umum', 'Penertiban Pasar'],
    ['Pedagang pakaian memakai badan jalan', 'Penertiban Pasar'],
    ['Lapak makanan menutup jalur evakuasi', 'Penertiban Pasar'],
    ['PKL berjualan di depan kantor', 'Penertiban Pasar'],
    ['Pedagang menaruh kursi di jalan umum', 'Penertiban Pasar'],
    ['Lapak menutup trotoar pasar tradisional', 'Penertiban Pasar'],
    ['Penjual ikan mengganggu kios lain', 'Penertiban Pasar'],
    ['Lapak berdiri di area taman pasar', 'Penertiban Pasar'],
    ['Pedagang menutup akses pemadam kebakaran', 'Penertiban Pasar'],
    ['Lapak malam hari tidak dibongkar', 'Penertiban Pasar'],
    ['Rak dagang dipaku ke fasilitas umum', 'Penertiban Pasar'],
    ['Pedagang membuka lapak tambahan', 'Penertiban Pasar'],
    ['Area bongkar muat dipakai berdagang', 'Penertiban Pasar'],
    ['Lapak berdiri di pintu keluar pasar', 'Penertiban Pasar'],
    ['Pedagang menguasai lebih dari satu kios', 'Penertiban Pasar'],
    ['Dagangan meluber ke badan jalan', 'Penertiban Pasar'],
    ['Lapak menutup jalur difabel', 'Penertiban Pasar'],
    ['PKL menggunakan bahu jalan pasar', 'Penertiban Pasar'],
    ['Lapak menutup akses parkir umum', 'Penertiban Pasar'],
    ['Tenda dagang berdiri di fasilitas umum', 'Penertiban Pasar'],
    ['Lapak berada di tikungan jalan', 'Penertiban Pasar'],
    ['Pedagang buah membuka lapak liar', 'Penertiban Pasar'],
    ['Penjual sayur menghalangi jalur masuk', 'Penertiban Pasar'],
    ['Lapak berdiri di depan halte', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan median jalan', 'Penertiban Pasar'],
    ['Lapak muncul di area terlarang pasar', 'Penertiban Pasar'],
    ['Pedagang memindahkan batas kios', 'Penertiban Pasar'],
    ['Lapak menutup akses toilet umum', 'Penertiban Pasar'],
    ['Pedagang berjualan di jalur sepeda', 'Penertiban Pasar'],
    ['Lapak menutup pintu darurat pasar', 'Penertiban Pasar'],
    ['Pedagang ikan mencuci di selokan', 'Penertiban Pasar'],
    ['PKL berjualan di depan rumah warga', 'Penertiban Pasar'],
    ['Lapak berdiri di bahu jalan utama', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan bahu trotoar', 'Penertiban Pasar'],
    ['Lapak mengganggu arus lalu lintas', 'Penertiban Pasar'],
    ['Pedagang menaruh barang di jalan', 'Penertiban Pasar'],
    ['Lapak liar berdiri tanpa retribusi', 'Penertiban Pasar'],
    ['Pedagang membuka kios darurat', 'Penertiban Pasar'],
    ['Lapak berdiri di jalur hijau', 'Penertiban Pasar'],
    ['Pedagang menghalangi pintu pasar', 'Penertiban Pasar'],
    ['Lapak melanggar jam operasional', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan selasar umum', 'Penertiban Pasar'],
    ['Lapak berdiri di depan masjid', 'Penertiban Pasar'],
    ['Pedagang menutup akses kendaraan', 'Penertiban Pasar'],
    ['Lapak mengganggu aktivitas warga', 'Penertiban Pasar'],
    ['Pedagang menambah meja di luar kios', 'Penertiban Pasar'],
    ['Lapak berdiri di area terlarang', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan bahu gang', 'Penertiban Pasar'],
    ['Lapak liar muncul saat malam', 'Penertiban Pasar'],
    ['Pedagang menutup jalur keluar masuk', 'Penertiban Pasar'],
    ['Lapak berdiri di depan klinik', 'Penertiban Pasar'],
    ['Pedagang menghalangi pejalan kaki', 'Penertiban Pasar'],
    ['Lapak menutup akses umum', 'Penertiban Pasar'],
    ['Pedagang membuka lapak tanpa izin', 'Penertiban Pasar'],
    ['Lapak berdiri di area sekolah', 'Penertiban Pasar'],
    ['Pedagang menggunakan badan jalan pasar', 'Penertiban Pasar'],
    ['Lapak menutup jalur kendaraan', 'Penertiban Pasar'],
    ['Pedagang menaruh dagangan di aspal', 'Penertiban Pasar'],
    ['Lapak berdiri di persimpangan', 'Penertiban Pasar'],
    ['Pedagang membuka lapak darurat', 'Penertiban Pasar'],
    ['Lapak liar mengganggu ketertiban', 'Penertiban Pasar'],
    ['Pedagang berjualan di jalur umum', 'Penertiban Pasar'],
    ['Lapak berdiri di area publik', 'Penertiban Pasar'],
    ['Pedagang menutup akses lingkungan', 'Penertiban Pasar'],
    ['Lapak mengganggu aktivitas pasar', 'Penertiban Pasar'],
    ['Pedagang melanggar aturan zonasi', 'Penertiban Pasar'],
    ['Lapak berdiri di depan rumah ibadah', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan ruang publik', 'Penertiban Pasar'],
    ['Lapak berdiri tanpa pengawasan', 'Penertiban Pasar'],
    ['Pedagang menutup jalur pejalan', 'Penertiban Pasar'],
    ['Lapak berdiri di lokasi terlarang', 'Penertiban Pasar'],
    ['Pedagang membuka lapak liar', 'Penertiban Pasar'],
    ['Lapak mengganggu ketertiban umum', 'Penertiban Pasar'],
    ['Pedagang berjualan di area bebas', 'Penertiban Pasar'],
    ['Lapak berdiri di luar pasar', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan ruang jalan', 'Penertiban Pasar'],
    ['Lapak berdiri sembarangan', 'Penertiban Pasar'],
    ['Pedagang menghalangi arus jalan', 'Penertiban Pasar'],
    ['Lapak menutup fasilitas umum', 'Penertiban Pasar'],
    ['Pedagang membuka lapak di luar area', 'Penertiban Pasar'],
    ['Lapak berdiri di badan trotoar', 'Penertiban Pasar'],
    ['Pedagang berjualan tanpa izin resmi', 'Penertiban Pasar'],
    ['Lapak mengganggu kenyamanan warga', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan bahu jalan umum', 'Penertiban Pasar'],
    ['Lapak berdiri di jalur ramai', 'Penertiban Pasar'],
    ['Pedagang membuka lapak tidak terdaftar', 'Penertiban Pasar'],
    ['Lapak berdiri di zona merah', 'Penertiban Pasar'],
    ['Pedagang menutup jalur publik', 'Penertiban Pasar'],
    ['Lapak mengganggu lalu lintas', 'Penertiban Pasar'],
    ['Pedagang membuka lapak sembarangan', 'Penertiban Pasar'],
    ['Lapak berdiri di area terlarang pasar', 'Penertiban Pasar'],
    ['Pedagang melanggar ketentuan pasar', 'Penertiban Pasar'],
    ['Lapak berdiri tanpa persetujuan', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan jalan lingkungan', 'Penertiban Pasar'],
    ['Lapak mengganggu ketertiban lingkungan', 'Penertiban Pasar'],
    ['Pedagang membuka lapak di luar jam', 'Penertiban Pasar'],
    ['Lapak berdiri di ruang publik', 'Penertiban Pasar'],
    ['Pedagang melanggar aturan berdagang', 'Penertiban Pasar'],
    ['Lapak berdiri tidak sesuai ketentuan', 'Penertiban Pasar'],
    ['Pedagang membuka lapak liar di pasar', 'Penertiban Pasar'],
    ['Lapak mengganggu aktivitas umum', 'Penertiban Pasar'],
    ['Pedagang berjualan di area terlarang', 'Penertiban Pasar'],
    ['Lapak berdiri di jalur umum', 'Penertiban Pasar'],
    ['Pedagang memanfaatkan bahu jalan kota', 'Penertiban Pasar'],
    ['Lapak menghalangi akses umum', 'Penertiban Pasar'],
    ['Pedagang membuka lapak tanpa izin pengelola', 'Penertiban Pasar'],
    ['Lapak berdiri di area publik pasar', 'Penertiban Pasar'],
    ['Pedagang melanggar tata tertib pasar', 'Penertiban Pasar'],

    // --- Klasifikasi: Sapi Liar ---
    ['Sapi berkeliaran di area perumahan', 'Sapi Liar'],
    ['Sapi terlihat di jalan umum', 'Sapi Liar'],
    ['Kawanan sapi melintas jalan desa', 'Sapi Liar'],
    ['Sapi lepas merusak tanaman warga', 'Sapi Liar'],
    ['Anak sapi tersesat di pemukiman', 'Sapi Liar'],
    ['Sapi buang kotoran di jalan', 'Sapi Liar'],
    ['Sapi berkeliaran tanpa pengawasan', 'Sapi Liar'],
    ['Sapi minum air di kolam kota', 'Sapi Liar'],
    ['Pengendara hampir menabrak sapi', 'Sapi Liar'],
    ['Sapi merobohkan pagar rumah', 'Sapi Liar'],
    ['Sapi tidur di tengah jalan', 'Sapi Liar'],
    ['Kandang kosong sapi berkeliaran', 'Sapi Liar'],
    ['Sapi jatuh ke selokan', 'Sapi Liar'],
    ['Sapi memakan sampah TPS', 'Sapi Liar'],
    ['Jejak sapi terlihat di lapangan', 'Sapi Liar'],
    ['Sapi masuk halaman rumah warga', 'Sapi Liar'],
    ['Sapi mengganggu lalu lintas', 'Sapi Liar'],
    ['Sapi berjalan di jalan raya', 'Sapi Liar'],
    ['Sapi terlihat di area pasar', 'Sapi Liar'],
    ['Sapi merusak tanaman kebun', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar sekolah', 'Sapi Liar'],
    ['Sapi masuk area perkantoran', 'Sapi Liar'],
    ['Sapi melintas di persimpangan', 'Sapi Liar'],
    ['Sapi berdiri di tengah jalan', 'Sapi Liar'],
    ['Sapi berkeliaran di malam hari', 'Sapi Liar'],
    ['Sapi masuk area pemukiman padat', 'Sapi Liar'],
    ['Sapi terlihat di jalur kendaraan', 'Sapi Liar'],
    ['Sapi mengganggu aktivitas warga', 'Sapi Liar'],
    ['Sapi masuk taman kota', 'Sapi Liar'],
    ['Sapi berkeliaran di area publik', 'Sapi Liar'],
    ['Sapi merusak tanaman hias', 'Sapi Liar'],
    ['Sapi berjalan di jalur utama', 'Sapi Liar'],
    ['Sapi terlihat di sekitar pasar', 'Sapi Liar'],
    ['Sapi mengotori jalan umum', 'Sapi Liar'],
    ['Sapi masuk halaman sekolah', 'Sapi Liar'],
    ['Sapi berkeliaran tanpa tali', 'Sapi Liar'],
    ['Sapi terlihat di jalan lingkungan', 'Sapi Liar'],
    ['Sapi menghalangi kendaraan', 'Sapi Liar'],
    ['Sapi masuk area pemukiman', 'Sapi Liar'],
    ['Sapi berjalan di bahu jalan', 'Sapi Liar'],
    ['Sapi terlihat di sekitar rumah', 'Sapi Liar'],
    ['Sapi berkeliaran di area terbuka', 'Sapi Liar'],
    ['Sapi masuk kebun warga', 'Sapi Liar'],
    ['Sapi melintas di jalan kecil', 'Sapi Liar'],
    ['Sapi terlihat di jalur umum', 'Sapi Liar'],
    ['Sapi mengganggu ketertiban', 'Sapi Liar'],
    ['Sapi masuk area publik', 'Sapi Liar'],
    ['Sapi berkeliaran di jalan kota', 'Sapi Liar'],
    ['Sapi terlihat di area ramai', 'Sapi Liar'],
    ['Sapi merusak pagar kebun', 'Sapi Liar'],
    ['Sapi masuk halaman kantor', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar taman', 'Sapi Liar'],
    ['Sapi terlihat di jalur ramai', 'Sapi Liar'],
    ['Sapi mengotori fasilitas umum', 'Sapi Liar'],
    ['Sapi masuk area perumahan', 'Sapi Liar'],
    ['Sapi berkeliaran di lingkungan warga', 'Sapi Liar'],
    ['Sapi terlihat di area terbuka', 'Sapi Liar'],
    ['Sapi mengganggu lalu lintas warga', 'Sapi Liar'],
    ['Sapi masuk area pasar tradisional', 'Sapi Liar'],
    ['Sapi berjalan di jalur kendaraan', 'Sapi Liar'],
    ['Sapi terlihat di area umum', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar rumah ibadah', 'Sapi Liar'],
    ['Sapi mengotori jalan lingkungan', 'Sapi Liar'],
    ['Sapi masuk area hijau', 'Sapi Liar'],
    ['Sapi terlihat di jalur publik', 'Sapi Liar'],
    ['Sapi berkeliaran di jalan utama', 'Sapi Liar'],
    ['Sapi masuk area pemukiman warga', 'Sapi Liar'],
    ['Sapi terlihat di sekitar fasilitas umum', 'Sapi Liar'],
    ['Sapi mengganggu aktivitas sehari-hari', 'Sapi Liar'],
    ['Sapi berkeliaran di area perdesaan', 'Sapi Liar'],
    ['Sapi terlihat di jalur desa', 'Sapi Liar'],
    ['Sapi masuk area publik warga', 'Sapi Liar'],
    ['Sapi mengotori lingkungan', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar pemukiman', 'Sapi Liar'],
    ['Sapi terlihat di jalur perumahan', 'Sapi Liar'],
    ['Sapi masuk area terbuka umum', 'Sapi Liar'],
    ['Sapi mengganggu ketenangan warga', 'Sapi Liar'],
    ['Sapi berkeliaran di area ramai', 'Sapi Liar'],
    ['Sapi terlihat di sekitar jalan raya', 'Sapi Liar'],
    ['Sapi masuk area umum warga', 'Sapi Liar'],
    ['Sapi mengotori jalan desa', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar lingkungan', 'Sapi Liar'],
    ['Sapi terlihat di jalur kota', 'Sapi Liar'],
    ['Sapi masuk area publik kota', 'Sapi Liar'],
    ['Sapi mengganggu aktivitas umum', 'Sapi Liar'],
    ['Sapi berkeliaran di area masyarakat', 'Sapi Liar'],
    ['Sapi terlihat di jalur lingkungan', 'Sapi Liar'],
    ['Sapi masuk area pemukiman kota', 'Sapi Liar'],
    ['Sapi mengotori fasilitas publik', 'Sapi Liar'],
    ['Sapi berkeliaran di sekitar wilayah warga', 'Sapi Liar'],
    ['Sapi terlihat di jalur umum kota', 'Sapi Liar'],
    ['Sapi masuk area lingkungan warga', 'Sapi Liar'],
    ['Sapi mengganggu ketertiban umum', 'Sapi Liar'],

    // --- Klasifikasi: Orang Bolos ---
    ['Siswa tidak masuk sekolah tanpa keterangan', 'Orang Bolos'],
    ['Pelajar bolos saat jam sekolah', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kuliah', 'Orang Bolos'],
    ['Siswa nongkrong di luar sekolah', 'Orang Bolos'],
    ['Karyawan mangkir dari pekerjaan', 'Orang Bolos'],
    ['Pelajar terlihat di warnet saat sekolah', 'Orang Bolos'],
    ['Guru tidak hadir mengajar', 'Orang Bolos'],
    ['Pekerja proyek tidak masuk kerja', 'Orang Bolos'],
    ['Murid bermain di luar saat sekolah', 'Orang Bolos'],
    ['Pegawai terlambat dan dicatat bolos', 'Orang Bolos'],
    ['Pelajar bolos ujian sekolah', 'Orang Bolos'],
    ['Petugas kebersihan tidak masuk kerja', 'Orang Bolos'],
    ['Buruh harian tidak hadir bekerja', 'Orang Bolos'],
    ['Siswa memalsukan surat sakit', 'Orang Bolos'],
    ['Staf kantor tidak berada di tempat', 'Orang Bolos'],
    ['Perawat absen tanpa izin', 'Orang Bolos'],
    ['Mahasiswa bolos praktikum', 'Orang Bolos'],
    ['Pelajar nongkrong di kafe saat sekolah', 'Orang Bolos'],
    ['Karyawan tidak masuk tanpa pemberitahuan', 'Orang Bolos'],
    ['Siswa keluar sekolah tanpa izin', 'Orang Bolos'],
    ['Pelajar bolos ke pusat perbelanjaan', 'Orang Bolos'],
    ['Mahasiswa tidak hadir ujian', 'Orang Bolos'],
    ['Pegawai meninggalkan kantor saat jam kerja', 'Orang Bolos'],
    ['Siswa bermain game saat sekolah', 'Orang Bolos'],
    ['Pelajar tidak kembali ke kelas', 'Orang Bolos'],
    ['Mahasiswa absen tanpa keterangan', 'Orang Bolos'],
    ['Karyawan pulang sebelum jam selesai', 'Orang Bolos'],
    ['Siswa tidak mengikuti pelajaran', 'Orang Bolos'],
    ['Pelajar nongkrong di warung', 'Orang Bolos'],
    ['Mahasiswa tidak hadir seminar', 'Orang Bolos'],
    ['Pegawai tidak mengikuti apel', 'Orang Bolos'],
    ['Siswa bolos ke lapangan', 'Orang Bolos'],
    ['Pelajar keluar sekolah saat jam pelajaran', 'Orang Bolos'],
    ['Mahasiswa tidak hadir bimbingan', 'Orang Bolos'],
    ['Karyawan tidak masuk kerja hari ini', 'Orang Bolos'],
    ['Siswa bermain di luar sekolah', 'Orang Bolos'],
    ['Pelajar bolos jam pertama', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kelas pagi', 'Orang Bolos'],
    ['Pegawai absen tanpa izin', 'Orang Bolos'],
    ['Siswa tidak mengikuti kegiatan sekolah', 'Orang Bolos'],
    ['Pelajar nongkrong saat jam pelajaran', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kuliah wajib', 'Orang Bolos'],
    ['Karyawan mangkir tanpa kabar', 'Orang Bolos'],
    ['Siswa keluar kelas tanpa izin', 'Orang Bolos'],
    ['Pelajar bolos jam terakhir', 'Orang Bolos'],
    ['Mahasiswa tidak hadir diskusi', 'Orang Bolos'],
    ['Pegawai tidak kembali setelah istirahat', 'Orang Bolos'],
    ['Siswa tidak masuk kelas', 'Orang Bolos'],
    ['Pelajar bolos ke tempat wisata', 'Orang Bolos'],
    ['Mahasiswa absen kegiatan kampus', 'Orang Bolos'],
    ['Karyawan tidak hadir briefing', 'Orang Bolos'],
    ['Siswa nongkrong di luar pagar sekolah', 'Orang Bolos'],
    ['Pelajar bolos pelajaran olahraga', 'Orang Bolos'],
    ['Mahasiswa tidak hadir perkuliahan', 'Orang Bolos'],
    ['Pegawai tidak hadir rapat', 'Orang Bolos'],
    ['Siswa bolos jam pelajaran inti', 'Orang Bolos'],
    ['Pelajar keluar sekolah lebih awal', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kelas siang', 'Orang Bolos'],
    ['Karyawan mangkir hari kerja', 'Orang Bolos'],
    ['Siswa tidak mengikuti ujian', 'Orang Bolos'],
    ['Pelajar bolos ke rumah teman', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kegiatan wajib', 'Orang Bolos'],
    ['Pegawai absen kerja hari ini', 'Orang Bolos'],
    ['Siswa tidak hadir tanpa alasan', 'Orang Bolos'],
    ['Pelajar nongkrong di jalan', 'Orang Bolos'],
    ['Mahasiswa tidak hadir praktikum wajib', 'Orang Bolos'],
    ['Karyawan tidak masuk kerja tanpa izin', 'Orang Bolos'],
    ['Siswa bolos jam pelajaran', 'Orang Bolos'],
    ['Pelajar keluar sekolah tanpa sepengetahuan', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kelas penting', 'Orang Bolos'],
    ['Pegawai tidak hadir tugas', 'Orang Bolos'],
    ['Siswa tidak masuk kelas hari ini', 'Orang Bolos'],
    ['Pelajar bolos dan bermain', 'Orang Bolos'],
    ['Mahasiswa absen perkuliahan', 'Orang Bolos'],
    ['Karyawan tidak hadir bekerja', 'Orang Bolos'],
    ['Siswa bolos tanpa keterangan', 'Orang Bolos'],
    ['Pelajar tidak mengikuti jam sekolah', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kelas reguler', 'Orang Bolos'],
    ['Pegawai mangkir jam kerja', 'Orang Bolos'],
    ['Siswa tidak mengikuti kegiatan belajar', 'Orang Bolos'],
    ['Pelajar bolos sekolah hari ini', 'Orang Bolos'],
    ['Mahasiswa tidak hadir pertemuan', 'Orang Bolos'],
    ['Karyawan absen tanpa laporan', 'Orang Bolos'],
    ['Siswa bolos dan nongkrong', 'Orang Bolos'],
    ['Pelajar keluar sekolah saat jam aktif', 'Orang Bolos'],
    ['Mahasiswa tidak hadir kelas wajib', 'Orang Bolos'],
    ['Pegawai tidak hadir jam kerja', 'Orang Bolos'],
];
foreach ($data as $row) {
    $pdo->prepare("INSERT INTO training_data(text_data, label) VALUES(?,?)")
        ->execute($row);
}

echo "Training dataset inserted.\n";
